ShortLinks/Models/DataContext.cs
using MySql.Data.Entity;
using System.Data.Entity;

namespace ShortLinks.Models
{
    [DbConfigurationType(typeof(MySqlEFConfiguration))]
    public class DataContext: DbContext
    {
        public DataContext(): base("MysqlConnection")
        {
            this.Configuration.ValidateOnSaveEnabled = false;
        }

        public DbSet<ShortLink> ShortLinks { get; set; }
    }
}

ShortLinks/Models/ShortLink.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ShortLinks.Models
{
    /// <summary>
    /// Сокращенный URL
    /// </summary>
    public class ShortLink
    {
        /// <summary>
        /// ID сокрщенного URL-а
        /// </summary>        
        public int ShortLinkID { get; set; }

        /// <summary>
        /// Длинный URL
        /// </summary>
        [Display(Name = "Длинный URL")]
        public string LongUrl { get; set; }

        /// <summary>
        /// Сокращенный URL
        /// </summary>
        [Display(Name = "Сокращенный URL")]
        public string ShortUrl { get; set; }

        /// <summary>
        /// Количество переходов
        /// </summary>
        [Display(Name = "Количество переходов")]
        public int RedirectCount { get; set; }

        /// <summary>
        /// Дата и время создания сокращенного URL-а
        /// </summary>
        [Display(Name = "Дата и время создания")]
        public DateTime CreateDateTime {get; set;}
    }
}

ShortLinks/Controllers/ShortLinksController.cs
using ShortLinks.Helpers;
using ShortLinks.Models;
using ShortLinks.Validations;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace ShortLinks.Controllers
{
    /// <summary>
    /// Класс контроллер сокращенного URL-а
    /// </summary>
    public class ShortLinksController : Controller
    {
        /// <summary>
        /// GET запрос на получения списка сокращенных URL-ов
        /// </summary>        
        public ActionResult Index()
        {
            var db = new DataContext();

            ViewBag.DomainName = System.Web.HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority).ToString();

            var shortLinks = db.ShortLinks.OrderByDescending(sh => sh.ShortLinkID);
            return View(shortLinks);
        }

        /// <summary>
        /// GET запрос на добавление нового сокращенного URL-а
        /// </summary> 
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// POST запрос на добавление нового сокращенного URL-а
        /// </summary> 
        [HttpPost]
        public ActionResult Create(ShortLink shortLink)
        {
            var validator = new HttpURLValidator();
            if (!validator.Validate(shortLink.LongUrl, out Uri resultURI, out string errMessage))
            {
                ModelState.AddModelError("", errMessage);
                return View();
            }

            var db = new DataContext();

            shortLink.LongUrl = resultURI.AbsoluteUri;
            shortLink.RedirectCount = 0;            
            shortLink.ShortUrl = UniqueKey.GetUniqueKey();
            shortLink.CreateDateTime = DateTime.Now;

            db.ShortLinks.Add(shortLink);
            db.SaveChanges();

            return RedirectToAction("Index");         
        }

        /// <summary>
        /// GET запрос на отображение сокращенного URL-а для дальнейшего изменения по ID сокращенного URL-а
        /// </summary>
        /// <param name="shortLinkID">ID сокращенного URL-а</param>        
        public ActionResult Edit(int shortLinkID)
        {
            var db = new DataContext();
            var shortLink = db.ShortLinks.Find(shortLinkID);
            if (shortLink == null)
            {
                throw new Exception($"1226. Не удалось найти сокращенного URL-а с указанным номером ID - {shortLinkID}");
            }

            return View(shortLink);
        }

        /// <summary>
        /// POST запрос для изменения сокращенного URL-а  по ID сокращенного URL-а
        /// </summary>
        /// <param name="product">Объект продукта, который требуется изменить</param>        
        [HttpPost]
        public ActionResult Edit(ShortLink _shortLink)
        {
            var validator = new ShortURLValidator();
            if (!validator.Validate(_shortLink, out Uri resultURI, out List<string> errMessages))
            {
                foreach(string errMessage in errMessages)
                {
                    ModelState.AddModelError("", errMessage);
                }
                
                return View();
            }

            var db = new DataContext();

            var shortLink = db.ShortLinks.Find(_shortLink.ShortLinkID);
            shortLink.LongUrl = _shortLink.LongUrl;
            shortLink.ShortUrl = _shortLink.ShortUrl;

            db.Entry(shortLink).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");           
        }

        /// <summary>
        /// GET запрос на отображение сокращенного URL-а для дальнейшего удаления по ID сокращенного URL-а
        /// </summary>
        /// <param name="id">ID сокращенного Url-а</param> 
        public ActionResult Delete(int shortLinkID)
        {
            var db = new DataContext();

            var shortLink = db.ShortLinks.Find(shortLinkID);

            return View(shortLink);
        }

        /// <summary>
        /// POST запрос для удаления сокращенного URL-а
        /// </summary>
        /// <param name="product">Объект продукта, который требуется изменить</param>   
        [HttpPost]
        public ActionResult Delete(ShortLink _shortLink)
        {
            var db = new DataContext();

            var shortLink = db.ShortLinks.Find(_shortLink.ShortLinkID);

            db.ShortLinks.Remove(shortLink);
            db.SaveChanges();

            return RedirectToAction("Index");          
        }

        /// <summary>
        /// Метод перенаправляет на длинную ссылку
        /// </summary>
        /// <param name="id">Сокращенная ссылка</param>        
        public ActionResult Redirect(string id)
        {
            var db = new DataContext();

            var shortLink = db.ShortLinks.Where(sh => sh.ShortUrl == id).FirstOrDefault();
            shortLink.RedirectCount++;

            db.Entry(shortLink).State = EntityState.Modified;
            db.SaveChanges();

            if (shortLink != null)
            {                
                return Content($"<script>window.location = '{shortLink.LongUrl}';</script>");
            }

            return View();
        }
    }
}

ShortLinks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("URL Shortener", "Index", "ShortLinks", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Список сокращенных URL-ов", "Index", "ShortLinks")</li>                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ShortLinks/Views/ShortLinks/Create.cshtml
@model ShortLinks.Models.ShortLink

@{
    ViewBag.Title = "Создать";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Сокращенный URL</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LongUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LongUrl, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите длинную ссылку для сокращения"} })
                @Html.ValidationMessageFor(model => model.LongUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Список сокращенных URL-ов", "Index", null, new { @class = "btn btn-primary active"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShortLinks/Views/ShortLinks/Delete.cshtml
@model ShortLinks.Models.ShortLink

@{
    ViewBag.Title = "Удалить";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h3>Вы действительно хотите удалить?</h3>
<div>
    <h4>Сокращенный URL</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LongUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LongUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RedirectCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RedirectCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDateTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-danger" /> |
            @Html.ActionLink("Список сокращенных URL-ов", "Index", null, new { @class="btn btn-primary active"})
        </div>
    }
</div>

ShortLinks/Views/ShortLinks/Edit.cshtml
@model ShortLinks.Models.ShortLink

@{
    ViewBag.Title = "Изменить";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Сокращенный URL</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ShortLinkID)

        <div class="form-group">
            @Html.LabelFor(model => model.LongUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LongUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LongUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Список сокращенных URL-ов", "Index", null, new { @class = "btn btn-primary active" })
</div>

ShortLinks/Views/ShortLinks/Index.cshtml
@model IEnumerable<ShortLinks.Models.ShortLink>

@{
    ViewBag.Title = "Список сокращенных URL-ов";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Создать", "Create", null, new { @class="btn btn-primary active"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LongUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShortUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RedirectCount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateDateTime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LongUrl)
        </td>
        <td>
            @{
                string shortUrl = ViewBag.DomainName + "/" + item.ShortUrl;
            }
            @Html.DisplayFor(modelItem => shortUrl)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RedirectCount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreateDateTime)
        </td>
        <td>
            <div class="btn-group">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown">
                    Действия <span style="font-size: 12px;">&#9660</span>
                </button>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Изменить", "Edit", new { shortLinkID = item.ShortLinkID })</li>
                    <li class="divider"></li>
                    <li> @Html.ActionLink("Удалить", "Delete", new { shortLinkID = item.ShortLinkID })</li>
                </ul>
            </div>
        </td>
    </tr>
}

</table>

ShortLinks/Views/ShortLinks/Redirect.cshtml
@{
    ViewBag.Title = "Сокращенный URL";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>К сожалению, ссылка, к которой вы обратились, не существует в нашем сервисе.</p> 
<p>Помните, что наши сокращенные ссылки чувствительны к регистру и могут содержать буквы и цифры.</p>